version: '3.8'

services:
  zookeeper:
      image: confluentinc/cp-zookeeper:7.3.3 
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"
      networks:
        - app-network
  kafka:
    image: confluentinc/cp-kafka:7.3.3 
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Map port 9092 cho truy cập từ host (EXTERNAL listener)
      # Port 29092 chỉ dùng nội bộ trong Docker, không cần map ra ngoài
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # Định nghĩa 2 listeners: INTERNAL cho nội bộ Docker, EXTERNAL cho host
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # Kafka lắng nghe trên port 29092 (INTERNAL) và 9092 (EXTERNAL) bên trong container
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      # Advertise đúng địa chỉ: kafka:29092 cho INTERNAL, localhost:9092 cho EXTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      # Listener cho giao tiếp giữa các broker (nếu có nhiều broker)
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Single node setup
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Allow auto-creation for dev convenience
      KAFKA_LOG_DIRS: '/var/lib/kafka/data' # Ensure Kafka data is stored in a volume
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network
    healthcheck:
        # Sử dụng listener INTERNAL (kafka:29092) cho healthcheck vì nó chạy trong mạng Docker
        test: ["CMD-SHELL", "/usr/bin/kafka-topics --bootstrap-server kafka:29092 --list"]
        interval: 10s
        timeout: 5s
        retries: 5
  elasticsearch:
    image: elasticsearch:8.14.0 # Use a specific recent version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # Important for single node setup
      - xpack.security.enabled=false # Disable security for dev (NOT FOR PRODUCTION)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limit memory usage
    ports:
      - "9200:9200"
      - "9300:9300" # Transport port
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
        test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=10s"]
        interval: 15s
        timeout: 15s
        retries: 10
        start_period: 30s
  app:
    build: .
    container_name: log_app
    ports:
      - "8080:8080"
    env_file:
    - .env
    environment:
      - SERVER_PORT=8080
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=todo_db
      # Đảm bảo app sử dụng listener INTERNAL
      - KAFKA_BROKERS=kafka:29092
      - ELASTICSEARCH_ADDRESSES=http://elasticsearch:9200
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        # Phụ thuộc vào healthcheck đã cập nhật
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./SparkLogs:/app/host_logs:ro
      - ./state:/app/state
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_db
      - MYSQL_PASSWORD=mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data: 
  kafka_data:
  es_data:
networks:
  app-network:
    driver: bridge
